tcp:
  services:
    master-eva:
      loadBalancer:
        servers:
          - address: "master_1:3306"
          - address: "master_2:3306"
          - address: "master_3:3306"

  routers:
    master-eva:
      # won't listen to entry point web
      entryPoints:
        - "mysql"
      rule: "HostSNI(`*`)"
      service: "master-eva"


