http:
  routers:
    http_router:
      rule: "Host(`localhost`)"
      service: webservers
    # https_router:
    #   rule: "Host(`traefik.yourdomain.com`)"
    #   service: allbackend
    #   tls:
    #     certResolver: myresolver
    #     options: tlsoptions
  services:
    webservers:
      loadBalancer:
        servers:
          - url: "http://eva1_web_1/"
