version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: bitteaendern
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: eva_tischtennis
      MYSQL_USER: knex
      MYSQL_PASSWORD: eva_tischtennis
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - private
      - db
    ports:
      - 3306:3306
    restart: unless-stopped
  web:
    image: eva/backend
    environment:
      PORT: 80
      DB_HOST: db
    networks:
      - private
      - traefik
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped

volumes:
  db_data: {}

networks:
  private:
  traefik:
    external: true
  db:
    external: true
