version: '2'

services:
  eva_traefik:
    image: traefik:latest
    container_name: eva_traefik
    command:
      - "--docker --docker.domain=localhost"
    ports:
      - 80:80
      - 8080:8080
    networks:
      - eva_traefik
    volumes:
      - ./config/traefik.yaml:/traefik.yaml
      - ./config/tls.yaml:/tls.yaml
    restart: unless-stopped

networks:
  eva_traefik:
    external: true
